### ISSUE TITLE
Hotfix - Add/Edit Drinks - spacing around input

### ISSUE THREAD

**Issue by jadrum** [jadrum/RestaurantManager#11]
When entering a field for drinks (i.e. a name), it allows extra space to be appended to the name. So if someone enters 'beer  ', the spaces would be included into the db. Probably want to trim spaces.

**Comment by jadrum** [comment]
also needs to be done to appetizers #4

**Comment by jadrum** [comment]
- [ ] also needs to be done to desserts #16

**Comment by dzdrum** [comment]
Accidentally committed to the wrong issue. Reference dde3c8a

**Comment by dzdrum** [comment]
Issue resolved with the above commit reference number.
