### ISSUE TITLE
Hotfix - Add/Edit Drinks - price input type

### ISSUE THREAD

**Issue by jadrum** [jadrum/RestaurantManager#12]
Currently when entering a price, it is saved to the Firebase DB as a string for some reason. We would preferably like for it to be saved as some sort of numerical input (i.e. double with 2 decimal places). 
We are getting: "12.3"
We want: 12.30, not 12.3, not 12.300

**Comment by jadrum** [comment]
- [ ] also needs to be done to appetizers #4

**Comment by jadrum** [comment]
- [ ] also needs to be done to desserts #16

**Comment by dzdrum** [comment]
Resolved the issue in the last commit.

**Comment by dzdrum** [comment]
Resolved the issue with above commit.
